fail_fast: true
repos:
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [file, python]
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [file, python]
